POST http://localhost:5173/users
Content-Type: application/json
{
	"firstName": "Alexandr",
	"lastName": "Axyonov",
	"email": "boobooboo@mail.ru",
	"password": "password123!"
}


POST http://localhost:5173/users/create-many
Content-Type: application/json
{
	"users" : [
		{
			"firstName": "Aleee",
			"lastName": "Axyo",
			"email": "boob@mail.ru",
			"password": "password123!"
		}
	]
}