POST http://localhost:5173/auth/refresh-tokens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoiYm9vYm9vYm9vQG1haWwucnUiLCJpYXQiOjE3NTgzNDM1ODgsImV4cCI6MTc1ODM0MzU5MSwiYXVkIjoibG9jYWxob3N0OjUxNzMiLCJpc3MiOiJsb2NhbGhvc3Q6NTE3MyJ9.ofpX-8y-9b5xXI0Zxgt-n69hQQsSA8b9EV1Z-7ToTrU

{
	"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImlhdCI6MTc1ODM0MzU4OCwiZXhwIjoxNzU4MzQzNjc0LCJhdWQiOiJsb2NhbGhvc3Q6NTE3MyIsImlzcyI6ImxvY2FsaG9zdDo1MTczIn0.ekFQFnlVbSpBjxgD9cAJVJ7_WkUSkJHoHyXaWMz1Z3U"
}